name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace --info

    - name: List build outputs (for debugging)
      run: find . -name "*.apk" -type f

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
